### ISSUE TITLE
Encrypting & Editing env

### ISSUE THREAD

**Issue by manikandanNeo** [React-Native-Nation/react-native-config-encrypted#3]
Can't understand the encrypting and editing process clearly. Can you give a step by step process on how to encrypt?

**Comment by jamesjara** [comment]
1. you must have a .env file already, for example: 
```
URL='https://www.google.com/'
```
2. select a key, let's say 'manika', run the cli script to generate the encrypted value based on the file-value in the step #1.
```
node_modules/.bin/env-config-encrypt .env manika URL
```
this will print the encrypted value of the key `URL` of the `.env` file. 

3.  Use the lib to access the encrypted value
```
const URL = Config.get('URL');
```

Remember to configure the lib with the key in order to be able to decrypt the value. 
```
Config.configure({
    key: 'manika',
    provider: ConfigProvider
});
```

**Comment by manikandanNeo** [comment]
Thank you so much for your reply. Now I'm able to encrypt and edit env.

**Comment by Gauravbtl** [comment]
I follow the same steps but getting an empty string  
```
Config.configure({
  key: 'keyvalue',
  provider: ConfigProvider
})

const URL = Config.get('URL'); 
console.log(URL) // Getting "" here 
```

//where  as 
```
const URL = Config.get('URL', false); 
console.log(URL) // Getting the raw value same as in .env file here 
```

**Comment by jamesjara** [comment]
Seems that your `URL` property is not really encrypted with your key `keyvalue`  , you have to encrypt your env properties with the cli cmd

**Comment by Gauravbtl** [comment]
> Seems that your `URL` property is not really encrypted with your key `keyvalue` , you have to encrypt your env properties with the cli cmd

The very first step I did to encrypt the value in .env file through the below command 

`$ node_modules/.bin/env-config-encrypt .env keyvalue URL`
and after that the value i got i directly put into env file 
`URL=CLI geranted value`
